/**
 * App: Picture Model
 * Package: com.picturemodel.domain.enums
 * File: MetadataSource.java
 * Version: 0.1.0
 * Turns: 5
 * Author: Bobwares (bobwares@outlook.com)
 * Date: 2026-01-30T02:03:52Z
 * Exports: MetadataSource
 * Description: enum MetadataSource for MetadataSource responsibilities. Methods: none (enum constants only).
 */

package com.picturemodel.domain.enums;

/**
 * Source of image metadata.
 *
 * @author Claude (AI Coding Agent)
 */
public enum MetadataSource {
    /**
     * Metadata extracted from EXIF data in the image file
     */
    EXIF,

    /**
     * Metadata manually entered by user
     */
    USER_ENTERED,

    /**
     * Metadata automatically generated by the system
     */
    AUTO_GENERATED
}
