# /**
#  * App: Picture Model
#  * Package: e2e
#  * File: crawler-start.http
#  * Version: 0.1.1
#  * Turns: 1,5
#  * Author: Bobwares (bobwares@outlook.com)
#  * Date: 2026-01-30T22:38:02Z
#  * Exports: N/A
#  * Description: Start a crawl job.
#  */
@baseUrl = http://localhost:8080

POST {{baseUrl}}/api/crawler/start
Content-Type: application/json
Accept: application/json

{
  "driveId": "51e11806-7000-4a1d-b4ee-52581fe1d683",
  "rootPath": "",
  "isIncremental": false
}
