# /**
#  * App: Picture Model
#  * Package: e2e
#  * File: drives-tree.http
#  * Version: 0.1.0
#  * Turns: 1
#  * Author: codex
#  * Date: 2026-01-29T22:54:22Z
#  * Exports: N/A
#  * Description: Get a drive directory tree.
#  */
@baseUrl = http://localhost:8080
@driveId = 00000000-0000-0000-0000-000000000000

GET {{baseUrl}}/api/drives/{{driveId}}/tree?path=/
Accept: application/json
