# /**
#  * App: Picture Model
#  * Package: e2e
#  * File: drives-update.http
#  * Version: 0.1.0
#  * Turns: 1
#  * Author: codex
#  * Date: 2026-01-29T22:54:22Z
#  * Exports: N/A
#  * Description: Update a drive.
#  */
@baseUrl = http://localhost:8080
@driveId = 00000000-0000-0000-0000-000000000000

PUT {{baseUrl}}/api/drives/{{driveId}}
Content-Type: application/json
Accept: application/json

{
  "name": "Updated Drive",
  "connection_url": "/tmp",
  "credentials": "{\"username\":\"user\",\"password\":\"pass\"}",
  "root_path": "/",
  "auto_connect": true,
  "auto_crawl": false
}
